BaseInfo:
  name: "prototype_fuckup_man"
  id: "testcard"
Health: 5
Damage: 3
cost: 1

triggers:
  on-summon:
    action: "DEAL_DAMAGE"
    target: "ENEMY"
    value: 2
  on-death:
    action: "DRAW_CARD"
    count: 1
